#Docker compose configuration edit by frank buzzlight.frank@qq.com
services:
  mysql:
    image: mysql
    container_name: mysql
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=next_horizon_db
    restart: always
    networks:
      - blog_network
    volumes:
      # 将 MySQL 数据挂载到 Windows 主机路径
      - C:/docker-volumes/mysql:/var/lib/mysql # 持久化 MySQL 数据库数据



  elasticsearch:
    image: elasticsearch:8.17.0
    container_name: es
    ports:
      - "9200:9200" # 将容器的 9200 端口映射到主机的 9200 端口
    environment:
      - discovery.type=single-node
      - xpack.security.http.ssl.enabled=false
      - xpack.license.self_generated.type=trial
      - xpack.security.enabled=false
      - ES_JAVA_OPTS=-Xms84m -Xmx512m
    networks:
      - blog_network
    depends_on:
      - mysql
      - redis
    volumes:
      # 将 Elasticsearch 数据和插件挂载到 Windows 主机路径
      - C:/docker-volumes/es_data:/usr/share/elasticsearch/data # 持久化 Elasticsearch 索引数据
      - C:/docker-volumes/es_plugins:/usr/share/elasticsearch/plugins # 持久化 Elasticsearch 插件

  redis:
    image: redis
    container_name: redis
    ports:
      - "6379:6379"
    restart: always
    networks:
      - blog_network
    depends_on:
      - mysql
    volumes:
      # 将 Redis 数据挂载到 Windows 主机路径
      - C:/docker-volumes/redis:/data # 持久化 Redis 缓存数据


  kibana:
    image: kibana:8.17.0
    container_name: kibana
    ports:
      - "5601:5601"
    environment:
      - "ELASTICSEARCH_HOSTS=http://es:9200"
    networks:
      - blog_network
    depends_on:
      - elasticsearch



networks:
  blog_network:
    driver: bridge

volumes:
  mysql_data: # 用于 MySQL 数据持久化
  es_data:    # 用于 Elasticsearch 索引持久化
  es_plugins: # 用于 Elasticsearch 插件持久化
  redis_data: # 用于 Redis 缓存持久化
